# Generated by Django 5.0.1 on 2024-02-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
