# Generated by Django 5.0.1 on 2024-02-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_feedback_email_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('0', 'Chưa phản hồi'), ('1', 'Đã phản hồi')], default='0', max_length=100),
        ),
    ]
