# Generated by Django 5.0.1 on 2024-02-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('0', 'Salary'), ('1', 'Business'), ('2', 'Side Hustle'), ('3', 'Other')], max_length=100),
        ),
    ]
